### ISSUE TITLE
Deploying to Google App Engine with Cloud SQL

### ISSUE THREAD

**Issue by benjie** [graphile/graphile.github.io#160]
@garcianavalon via Discord https://discordapp.com/channels/489127045289476126/498852330754801666/623461041430462464

This is the config, using PostGraphile as a library. `flex` is needed if you want websocket (subscriptions) support.

```
runtime: nodejs
env: flex

env_variables:
  PGUSER: 'your-database-user'
  PGHOST: '/cloudsql/your-cloudsql-instance-connection-string'
  PGPASSWORD: 'your-password'
  PGDATABASE: 'your-database-name'

beta_settings:
  cloud_sql_instances: your-cloudsql-instance-connection-string
```
